services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis_geoserver
    restart: unless-stopped
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - geoserver_postgis_data:/var/lib/postgresql/data
    networks:
      gis_network:
        aliases:
          - postgis_geoserver
          - spatial_db

  geoserver:
    image: kartoza/geoserver:2.28.2
    container_name: geoserver_ikya
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./proyek-gis/data_raster:/data_raster
      - ./proyek-gis/data_vector:/data_vector
    depends_on:
      - postgis
    networks:
      gis_network:
        aliases:
          - geoserver
          - geoserver_ikya

  geoserver-microservice:
    build: .
    container_name: geoserver-microservice
    restart: unless-stopped
    ports:
      - "8005:8001"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./proyek-gis/data_raster:/data_raster
      - ./proyek-gis/data_vector:/data_vector
    depends_on:
      - postgis
      - geoserver
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload --reload-dir /app/app
    networks:
      - gis_network

volumes:
  geoserver_postgis_data:

networks:
  gis_network:
    name: network_gis
    external: true
